apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: hpc-client-app
spec:
  replicas: 1  # Number of replicas, adjust if you need to scale
  selector:
    matchLabels:
      app: hpc-client-app
  template:
    metadata:
      labels:
        app: hpc-client-app
    spec:
      containers:
        - name: hpc-client-app-container
          image: {{ .Values.server.image }}:{{ .Values.server.tag }}    #when we use private repository install on server instead of public dockerHub then we have to give the path of image, where image have been uploaded in private repo.
          ports:
            - containerPort: 8080
