apiVersion: v1
kind: Service
metadata:
  name: hpcserver
spec:
  selector:
    app: hpc-client-app
  ports:
    - protocol: TCP
      port: 8080     # Service port that can be accessed externally
      targetPort: 8080  # Container port the app listens to
  type: ClusterIP  # Expose it via a LoadBalancer or NodePort if needed
